all:
  children:
    system:
      hosts:
        prometheus:
          acme_dns_reg_cert_domains:
          - prometheus.hc.deney.io
          acme_dns_replicate_registration: []
          additional_disk_device_path: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_incus_data
          ansible_host: 10.10.30.11
          certbot_domains:
          - prometheus.hc.deney.io
          fq_hostname: prometheus.hc.deney.io
          net_default_gateway: 10.10.30.1
          net_dns: 10.10.30.3
          static_ipv4_to_use: 10.10.30.11
    tofu_vars:
      children:
        system: {}
