location: dependencies
sources:
  - repo: git@github.com:mttjohnson/infra-components.git
    name: mttjohnson_infra
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
default_group: ''
groups:
  -
sources_locked:
  - repo: git@github.com:mttjohnson/infra-components.git
    name: mttjohnson_infra
    rev: be8ab95b620ff0f365ef55a5493e93029b417382
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
