location: dependencies
sources:
  - repo: git@github.com:mttjohnson/infra-components.git
    name: mttjohnson_infra
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
default_group: ''
groups:
  -
sources_locked:
  - repo: git@github.com:mttjohnson/infra-components.git
    name: mttjohnson_infra
    rev: 9d47f20dc54df3b7cec01a5b0f16156fb9f71c17
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
