location: dependencies
sources:
  - repo: git@github.com:mttjohnson/infra-components.git
    name: mttjohnson_infra
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
default_group: ''
groups:
  -
sources_locked:
  - repo: git@github.com:mttjohnson/infra-components.git
    name: mttjohnson_infra
    rev: d4014627a1adbbfa3c12a76f4cd7d62395482678
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
