all:
  children:
    system:
      hosts:
        exp-incus-standalone:
          acme_dns_reg_cert_domains: []
          acme_dns_replicate_registration: []
          additional_disk_device_path: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_incus_data
          ansible_host: 10.10.30.16
          attached_data_disk_type: block
          certbot_domains: []
          fq_hostname: exp-incus-standalone.hc.deney.io
          net_default_gateway: 10.10.30.1
          net_dns: 10.10.30.3
          static_ipv4_to_use: 10.10.30.16
    tofu_vars:
      children:
        system: {}
